models:
  GPT-4o: skip
  GPT-4.1: skip
  GPT-5: skip
  GPT-5-mini: skip
  GPT-5-nano: skip
  GPT-o3: skip
  GPT-o4-mini: skip
  Gemini 2.0 Flash: latest
  Gemini 2.5 Flash: skip
  Gemini 2.5 Pro: skip
  Claude 3.7 Sonnet: skip
  Claude 4.1 Sonnet: skip
  Claude 4.0 Sonnet: skip
  Claude 4.1 Opus: skip
  Claude 4.0 Opus: skip
  DeepSeek v3: skip
  DeepSeek R1: skip
  LLaMA Maverick: skip

query_results_dir: "query_results"
eval_results_dir: "eval_results"
num_queries: 1
huggingface_dataset_name: "JVRoggeveen/HARDMath2"